spring:
  application:
    name: sdms-backend

  datasource:
    url: jdbc:postgresql://pg-3d6c2daf-sendbox827-1d5a.c.aivencloud.com:28679/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_BUGHgY7tT_Dwohis5sa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 63f4945d921d599f27ae4fdf5bada3f1a1b2c3d4e5f678901234567890abcdef

file:
  upload-dir: uploads/

aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region:
      static: us-east-1 # US East (N. Virginia)
    stack:
      auto: false  # Prevents Spring Cloud from auto-configuring CloudFormation stack
  s3:
    bucket:
      name: sdmsfilesmanager
logging:
  level:
    org:
      springframework:
        security: DEBUG